// Code generated by goctl. DO NOT EDIT.
// Source: qrcode.proto

package server

import (
	"context"

	"shorturl-v2/rpc/qrcode/internal/logic"
	"shorturl-v2/rpc/qrcode/internal/svc"
	"shorturl-v2/rpc/qrcode/qrcode"
)

type QrcoderServer struct {
	svcCtx *svc.ServiceContext
	qrcode.UnimplementedQrcoderServer
}

func NewQrcoderServer(svcCtx *svc.ServiceContext) *QrcoderServer {
	return &QrcoderServer{
		svcCtx: svcCtx,
	}
}

func (s *QrcoderServer) GenQrcode(ctx context.Context, in *qrcode.QrcodeRequest) (*qrcode.QrcodeResponse, error) {
	l := logic.NewGenQrcodeLogic(ctx, s.svcCtx)
	return l.GenQrcode(in)
}
