// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: qrcode.proto

package qrcode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QrcodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *QrcodeRequest) Reset() {
	*x = QrcodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qrcode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QrcodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrcodeRequest) ProtoMessage() {}

func (x *QrcodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qrcode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrcodeRequest.ProtoReflect.Descriptor instead.
func (*QrcodeRequest) Descriptor() ([]byte, []int) {
	return file_qrcode_proto_rawDescGZIP(), []int{0}
}

func (x *QrcodeRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type QrcodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QrcodeData string `protobuf:"bytes,1,opt,name=QrcodeData,proto3" json:"QrcodeData,omitempty"`
}

func (x *QrcodeResponse) Reset() {
	*x = QrcodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qrcode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QrcodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QrcodeResponse) ProtoMessage() {}

func (x *QrcodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qrcode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QrcodeResponse.ProtoReflect.Descriptor instead.
func (*QrcodeResponse) Descriptor() ([]byte, []int) {
	return file_qrcode_proto_rawDescGZIP(), []int{1}
}

func (x *QrcodeResponse) GetQrcodeData() string {
	if x != nil {
		return x.QrcodeData
	}
	return ""
}

var File_qrcode_proto protoreflect.FileDescriptor

var file_qrcode_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x71, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x71, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22, 0x30, 0x0a, 0x0e, 0x51, 0x72, 0x63,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x51,
	0x72, 0x63, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x32, 0x45, 0x0a, 0x07, 0x51,
	0x72, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x51, 0x72, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x15, 0x2e, 0x71, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x51, 0x72, 0x63,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x71, 0x72, 0x63,
	0x6f, 0x64, 0x65, 0x2e, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x71, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qrcode_proto_rawDescOnce sync.Once
	file_qrcode_proto_rawDescData = file_qrcode_proto_rawDesc
)

func file_qrcode_proto_rawDescGZIP() []byte {
	file_qrcode_proto_rawDescOnce.Do(func() {
		file_qrcode_proto_rawDescData = protoimpl.X.CompressGZIP(file_qrcode_proto_rawDescData)
	})
	return file_qrcode_proto_rawDescData
}

var file_qrcode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_qrcode_proto_goTypes = []interface{}{
	(*QrcodeRequest)(nil),  // 0: qrcode.QrcodeRequest
	(*QrcodeResponse)(nil), // 1: qrcode.QrcodeResponse
}
var file_qrcode_proto_depIdxs = []int32{
	0, // 0: qrcode.Qrcoder.GenQrcode:input_type -> qrcode.QrcodeRequest
	1, // 1: qrcode.Qrcoder.GenQrcode:output_type -> qrcode.QrcodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qrcode_proto_init() }
func file_qrcode_proto_init() {
	if File_qrcode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qrcode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QrcodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qrcode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QrcodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qrcode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qrcode_proto_goTypes,
		DependencyIndexes: file_qrcode_proto_depIdxs,
		MessageInfos:      file_qrcode_proto_msgTypes,
	}.Build()
	File_qrcode_proto = out.File
	file_qrcode_proto_rawDesc = nil
	file_qrcode_proto_goTypes = nil
	file_qrcode_proto_depIdxs = nil
}
