// Code generated by goctl. DO NOT EDIT.
package types

type ShortenRequest struct {
	OriginalURL string `json:"original_url"`
	CustomAlias string `json:"custom_alias"` // optional
}

type ShortenResponse struct {
	ShortURL string `json:"short_url"`
}

type GetOriginalURLRequest struct {
	ShortURL string `json:"short_url"`
}

type GetOriginalURLResponse struct {
	OriginalURL string `json:"original_url"`
}

type Empty struct {
}
