// Code generated by goctl. DO NOT EDIT.
// Source: qrcode.proto

package qrcoder

import (
	"context"

	"shorturl-v2/rpc/qrcode/qrcode"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	QrcodeRequest  = qrcode.QrcodeRequest
	QrcodeResponse = qrcode.QrcodeResponse

	Qrcoder interface {
		GenQrcode(ctx context.Context, in *QrcodeRequest, opts ...grpc.CallOption) (*QrcodeResponse, error)
	}

	defaultQrcoder struct {
		cli zrpc.Client
	}
)

func NewQrcoder(cli zrpc.Client) Qrcoder {
	return &defaultQrcoder{
		cli: cli,
	}
}

func (m *defaultQrcoder) GenQrcode(ctx context.Context, in *QrcodeRequest, opts ...grpc.CallOption) (*QrcodeResponse, error) {
	client := qrcode.NewQrcoderClient(m.cli.Conn())
	return client.GenQrcode(ctx, in, opts...)
}
