// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"shorturl-v2/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/shorten",
				Handler: ShortenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/expand",
				Handler: ExpandHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:alias",
				Handler: RedirectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/qrcode",
				Handler: GenQrcodeHandler(serverCtx),
			},
		},
	)
}
