// Code generated by goctl. DO NOT EDIT.
// Source: transform.proto

package server

import (
	"context"

	"shorturl-v2/rpc/transform/internal/logic"
	"shorturl-v2/rpc/transform/internal/svc"
	"shorturl-v2/rpc/transform/transform"
)

type TransformerServer struct {
	svcCtx *svc.ServiceContext
	transform.UnimplementedTransformerServer
}

func NewTransformerServer(svcCtx *svc.ServiceContext) *TransformerServer {
	return &TransformerServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformerServer) GetShortURL(ctx context.Context, in *transform.ShortenRequest) (*transform.ShortenResponse, error) {
	l := logic.NewGetShortURLLogic(ctx, s.svcCtx)
	return l.GetShortURL(in)
}

func (s *TransformerServer) GetOriginalURL(ctx context.Context, in *transform.GetOriginalURLRequest) (*transform.GetOriginalURLResponse, error) {
	l := logic.NewGetOriginalURLLogic(ctx, s.svcCtx)
	return l.GetOriginalURL(in)
}

func (s *TransformerServer) Redirect(ctx context.Context, in *transform.Empty) (*transform.Empty, error) {
	l := logic.NewRedirectLogic(ctx, s.svcCtx)
	return l.Redirect(in)
}
