// Code generated by goctl. DO NOT EDIT.
// Source: transform.proto

package server

import (
	"context"

	"shorturl-v2/rpc/transform/internal/logic"
	"shorturl-v2/rpc/transform/internal/svc"
	"shorturl-v2/rpc/transform/transform"
)

type TransformerServer struct {
	svcCtx *svc.ServiceContext
	transform.UnimplementedTransformerServer
}

func NewTransformerServer(svcCtx *svc.ServiceContext) *TransformerServer {
	return &TransformerServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformerServer) Shorten(ctx context.Context, in *transform.ShortenRequest) (*transform.ShortenResponse, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}

func (s *TransformerServer) Expand(ctx context.Context, in *transform.ExpandRequest) (*transform.ExpandResponse, error) {
	l := logic.NewExpandLogic(ctx, s.svcCtx)
	return l.Expand(in)
}
