name: CICD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d

      - name: Check Containers are Healthy
        run: |
          sleep 60
          docker ps
          docker-compose ps
          if docker ps | grep "unhealthy"; then
            echo "Some containers are unhealthy"
            exit 1
          fi

      - name: Teardown
        run: docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            mkdir -p ~/workspace
            cd ~/workspace/
            rm -rf ./shorturl
            git clone --depth=1 git@github.com:jfeng986/shorturl-v2.git shorturl
            cd shorturl
            docker compose down
            docker compose build --no-cache --compress
            docker compose up -d
