name: CICD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Build and push Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          command_timeout: 20m
          script: |
            mkdir -p ~/workspace
            cd ~/workspace/
            rm -rf ./shorturl
            git clone --depth=1 git@github.com:jfeng986/shorturl-v2.git shorturl
            cd shorturl/gateway
            echo "ALLOWED_ORIGIN=${{ secrets.ALLOWED_ORIGIN }}" > .env
            cd ../
            cd web
            echo "VITE_API_HOST=${{ secrets.VITE_API_HOST }}\n" > .env
            echo "VITE_PORT=${{ secrets.VITE_PORT }}" >> .env
            cd ../
            sudo docker compose down

            sudo docker compose build --no-cache --compress
            sudo docker compose up -d
